name: test

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch
      - run: git commit --allow-empty -m "$(date +%FT%T)"
      - run: git push origin main
